spring:
  application:
    name: gateway
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
logging:
  level:
    org.springframework.security: TRACE