server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://avdeev-sa.ru/keycloak/realms/booking_realm
            user-name-attribute: preferred_username
        registration:
          gateway:
            provider: keycloak
            client-id: booking
            authorized-grant-types: authorization_code
            client-secret: '{cipher}878712b1da2988529855ad3d93671d350de72f4cff05a8a160ea684ac7f8f2b5ebe569546e613f742be00980a63c66cb5aea8ceffd6e869724c5a328de3a0d2f'
            scope: openid
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/v1/storage/**, /api/v1/contact-type/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/api/v1/work-time,/api/v1/calendar,/api/v1/reserve,/api/v1/calendar/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - TokenRelay=