server:
  port: 8082
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1
            - PrefixPath=/