server:
  port: 8083
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/v1/storage/**, /api/v1/contact-type/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/api/v1/work-time,/api/v1/calendar?,/api/v1/calendar/**
          filters:
            - StripPrefix=1
            - PrefixPath=/