server:
  port: 8083
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/v1/storage/**
            - Path=/api/v1/contact-type/**
          filters:
            - StripPrefix=1
            - PrefixPath=/