server:
  port: 0
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/booking
    name: postgresql
    username: resource
    password: 61Ifhjukjn
    schema: "resource"
    repositories:
      enabled: true