server:
  port: 0
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/booking
    name: postgresql
    username: resource
    password: '{cipher}eb56138ad5beb09bef691268bd396082251b65a51e1bc81b90d2da3532fd7aea'
    schema: "resource"
    repositories:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://avdeev-sa.ru/keycloak/realms/booking_realm
          jwk-set-uri: https://avdeev-sa.ru/keycloak/realms/booking_realm/protocol/openid-connect/certs
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/booking
    user: resource
    password: '{cipher}eb56138ad5beb09bef691268bd396082251b65a51e1bc81b90d2da3532fd7aea'
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure: "health,info"
  endpoint:
    info:
      enabled: true
      build:
        enabled: true
    health:
      enabled: true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.web.reactive: DEBUG