#!groovy

properties([disableConcurrentBuilds()])

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("Build artifacts") {
            steps {
                echo "=========start build arctifacts========="
                sh 'mvn clean package'
            }
        }
        stage("Remover containers") {
            steps {
                sh 'docker ps -aq --filter "name=config-server" | xargs -r docker rm -f'
                sh 'docker ps -aq --filter "name=gateway" | xargs -r docker rm -f'
                sh 'docker ps -aq --filter "name=eureka" | xargs -r docker rm -f'
            }
        }
        stage("Remove images") {
            steps {
                echo "Done"
            }
        }
        stage("Deploy") {
            steps {
                dir('eureka') {
                    sh 'docker build --tag eureka:1-snapshot .'
                }
                sh 'docker run -d --rm -p 8761:8761 --name eureka --network cloud eureka:1-snapshot'
            }
        }
    }
}