server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sergeiavdeev/config-server-src.git
          default-label: master
          #skip-ssl-validation: true
          #username:
          #password:
          search-paths:
            - /config
          clone-on-start: true
  application:
    name: config-server