server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sergeiavdeev/market-a
          default-label: master
          search-paths:
            - /config-service/src/main/resources/config
          clone-on-start: true
        #native:
        #  search-locations:
        #    - classpath:/config
  application:
    name: config-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${random.value}